### ISSUE TITLE
fixes to Translation object

### ISSUE THREAD

**Issue by balmas** [alpheios-project/data-models#17]
- [x] change lemma property to lemmaWord and have it contain just the lemma word itself to avoid a circular reference
- [x] add a String property to hold the language code of the translation 
- [x] rename the meanings property to glosses and make it array rather than a String of the joined list

**Comment by irina060981** [comment]
I have fixed the issues and commit changes to 

alpheios-project/data-models#lemma-client
alpheios-project/lemma-client#master
alpheios-project/components#lemma-client
