### ISSUE TITLE
obey text direction when calculating form property of Inflection

### ISSUE THREAD

**Issue by balmas** [alpheios-project/data-models#22]
the Inflection getter for form creates it by concatonating the prefix suffix and stem. this needs to obey the text direction for the language (e.g. for Arabic it should be prefix - stem - suffix from RTL)

**Comment by irina060981** [comment]
https://github.com/alpheios-project/data-models/pull/28

Changed Inflection.js get form method - use language model direction for generating a form

**Comment by irina060981** [comment]
Also in inflection-tables - the same method is used when views are generated.
View class / render method 
This method generates the forms for inflections (without using model language direction or form method of the Inflection class) and created forms attribute of the View.

And Inflections component used (before issue#100) forms generated in the render method.
May be we should fix it there too?

**Comment by balmas** [comment]
If all places that show the form can reference it from inflections.form that would be ideal.

**Comment by balmas** [comment]
So maybe means we can just remove that code from the render of the inflection-tables view class now?

**Comment by irina060981** [comment]
I think that we could remove this code from inflection-tables view render method if it is used only in webextension. Are there other tools that could use it?

**Comment by balmas** [comment]
Right now just the embedded library, the pwa and the webextension, but all use it through the inflection component and not directly so I think it should be fine.

**Comment by irina060981** [comment]
Ok , I have done it
https://github.com/alpheios-project/inflection-tables/pull/47

Bridget, I tried to execute tests - but they are all failed.
I didn't investigate it - should I do it on the next week?

**Comment by balmas** [comment]
Thank you!
I think the inflection table tests have been failing for awhile. But I would probably prefer to put the time into porting the inflection tables to the newer vue-components than writing unit tests for the older ones.

**Comment by balmas** [comment]
@monzug can you test that we are always displaying the stem, suffix and prefix in the proper direction for arabic now? (persian too, but it is harder to test because the parser is often failing to give us this information)

**Comment by monzug** [comment]
Honestly I am not sure how to test this one. I lookup some Persian and Arabic words and both the translation and the display very good

**Comment by balmas** [comment]
I think that's sufficient then. We can reopen if users report errors.
