### ISSUE TITLE
Store source information in a Definitions object

### ISSUE THREAD

**Issue by kirlat** [alpheios-project/data-models#5]
Short and full definitions can come form different sources. I think it will be beneficial to store some information about the source of origin within a Definition object. As a minimum, we can probably store a source URI and a description.

**Comment by balmas** [comment]
I actually forgot that I already did this with the ResourceProviderProxy. The Lexicon Client was returning Definition objects wrapped in ResourceProviderProxy objects.  I really liked the design, but I think it maybe doesn't work so well when we are passing objects been background and content scripts and have to reserialize them from JSON.
