### ISSUE TITLE
greek input normalization should allow &apos; for unicode 1fbd (greek koronis)

### ISSUE THREAD

**Issue by balmas** [alpheios-project/data-models#61]
Examples from alpheios-project/inflection-tables#211

'> Lexical query produces no results for some Greek words with accents. When double-clicking on them, the accent is left out. lookup for these words works fine. Words such as:
> οὐδ'
> δ'
> πότνι'
> ἀλλ'

**Comment by balmas** [comment]
With this change, apostrophes will be considered a part of a greek word, rather than removed.  For this not to have adverse impact when an apostrophe is meant as an apostrophe and not a greek koronis, it required the change to the morphology service as described in alpheios-project/morph-svc#16 to enable it to retry words Greek that are passed to it that contain an apostrophe if they fail.

It is possible that this could result in the wrong behavior if the word has an apostrophe that is used as an apostrophe AND which is actually a valid word if the apostrophe was mean to be a koronis.

(e.g. if both οὐδ' and οὐδ are valid words, and the author of the page was quoting the word οὐδ rather than trying to say οὐδ')

**Comment by monzug** [comment]
tested with οὐδ'  οὐδ  'οὐδ'  'οὐδ' - only the first one has a morphology output
I could not find any example of valid word with and without accent
