### ISSUE TITLE
make sure TextQuoteSelector works for RTL languages

### ISSUE THREAD

**Issue by balmas** [alpheios-project/data-models#75]
We need to make sure the textquoteselector works properly for RTL languages.

**Comment by balmas** [comment]
@monzug can you do some testing with the wordlist in arabic and persian and make sure the context is stored correctly?

**Comment by monzug** [comment]
I was able to add Persian, Arabic  and geez words in wordlist. 
see screenshots
![persina-worlist](https://user-images.githubusercontent.com/41396793/61814150-65625480-ae15-11e9-84ac-511283807520.JPG)

![arabic](https://user-images.githubusercontent.com/41396793/61814870-069dda80-ae17-11e9-85fb-8deaf900269e.JPG)

limits work here too (ascending/descending also for what I could see...) - I am not sure if we need to change the cursor for limit to exact word and lemma to be right to left, @balmas ?
 the limit by exact word did work for me when I paste a word from my list.  for limit to lemma, I used one of the saved word and click on it.

**Comment by balmas** [comment]
>limits work here too (ascending/descending also for what I could see...) - I am not sure if we need to change the cursor for limit to exact word and lemma to be right to left

Yes, I think we should change text direction for input of exact word to rtl for arabic and persian. Actually, we probably should do the same for the lookup box too, right? I will make this a new issue.

**Comment by monzug** [comment]
I am not sure because it does work everywhere (lookup and limit)
