### ISSUE TITLE
merge of two wordlist items fails

### ISSUE THREAD

**Issue by balmas** [alpheios-project/data-models#85]
the  WordItem.merge function is expected to return the updated merge item but it does not.
This causes an unexpected error in the case where a word somehow ends up twice in the same list (which should not be possible, but we found it to be the case with a test account)

reported by @monzug

**Comment by monzug** [comment]
to repro, use id: test@test.it

**Comment by balmas** [comment]
QA-3.0.1.72

**Comment by monzug** [comment]
I could log in as user test and see my loooong wordlist, I was also able to add new words.
